### ISSUE TITLE
Shortcuts don't use the query params

### ISSUE THREAD

**Issue by poi33** [enonic/npm-nextjs-adapter#328]
Its possible to add paramters to the shortcut.
Currently they are ignored by the shortcut implementation
![image](https://github.com/enonic/nextjs-adapter/assets/3340349/589a60c7-fa2b-4378-a3f4-a7fde67b1e4c)

**Comment by mortyeriksen** [comment]
Works! 

Test url: https://www.enonic-qa.com/resources/enonic-xp-all-you-need-to-know
