### ISSUE TITLE
getUrl malforming external urls

### ISSUE THREAD

**Issue by pfrang** [enonic/npm-nextjs-adapter#585]
Hi,

When passing in external urls, such as https://google.com, getUrl malforms the url ( see picture where href is the original href passed in to getUrl, while hrefAccountedForPreview is the result of getUrl).  https://google.com turns into /s://google.com, why?

I would expect / hope the getUrl function to only strip path from guillotine api endpoint if that exists, like it does on the first key value pair, becuase it gets that from the meta object, and leave all other links as is. The edge-case being paths to media/attachments, it shouldn't touch those either. 

We are on     "@enonic/nextjs-adapter": "^2.0.2", because we are still on /pages router. Is this dealt with in v3 or is it expected for users to implement the logic themselves?

![image](https://github.com/enonic/nextjs-adapter/assets/85552255/0dc25c7e-159e-42f1-8cfb-50ded4ceb5df)

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/npm-nextjs-adapter/issues/617

**Comment by pmi** [comment]
@pfrang version 2 of nextjs-adapter including this fix is available at https://www.npmjs.com/package/@enonic/nextjs-adapter/v/2.0.3
