### ISSUE TITLE
Links with tags inside don't work

### ISSUE THREAD

**Issue by alansemenov** [enonic/npm-nextjs-adapter#587]
A random, but functional link in a blog post is not showing live. Other links in the same blog posts are shown, though.

![image](https://github.com/enonic/nextjs-adapter/assets/11612490/842fbdb2-47ac-408e-935e-7ca18ac17796)

Behind the scenes:
![image](https://github.com/enonic/nextjs-adapter/assets/11612490/7d295fe6-2fe1-4db0-97ab-380b067789b5)

If I click the link in Content Studio, the link menu displays a content item. So it's working. But not shown.

https://www.enonic.com/blog/biggest-trends-content-tech-interview-thomas-sigdestad

https://xp.enonic.com/tool/com.enonic.app.contentstudio/main/enonic-homepage/edit/acab20c5-5573-424b-b348-bbcae2ab3c71

**Comment by mortyeriksen** [comment]
Looks good!

**Comment by vot-enonic** [comment]
Not so fast! I discovered something on prod.

The hyperlink text in italics, "Her er noen beste praksiser for bildehåndtering for nettinnhold »" is not present in the preview, although it is in the HtmlArea.

![image](https://github.com/enonic/npm-nextjs-adapter/assets/43465080/144c7284-06f6-46d5-90e3-602394bbbfa3)

The markup is: <p><a href="content://cd6d31b5-e7c7-4087-9c16-edfda6e32289"><em>Her er noen beste praksiser for bildehåndtering for nettinnhold »</em></a></p>

And it seems fine in the HtmlArea, editable and all. It just won't show up in preview.

**Comment by pmi** [comment]
Was it deployed to prod already @alansemenov ?
I fixed it in the next branch.

**Comment by alansemenov** [comment]
Only on QA, to get the fixes approved. I'll deploy to prod now.
